name: Projet MobDesign

on:
    push:
        branches: [main]

jobs:
  build-login-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Let's build the Docker image
        run: docker build -t mob-design .

      - name: Let's list the Docker images
        run: docker images

      - name: Let's login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Check the Docker images before pushing
        run: docker images

      - name: Now let's push the Docker image !
        run: |
            docker tag mob-design ${{ secrets.DOCKER_USERNAME }}/mob-design:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/mob-design:latest

  ftp-deploy:
    needs: build-login-push  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Installing Node.js and npm to run the build without commit the ./dist folder
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build


      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Local folder to deploy
          local-dir: ./dist/
          # Remote folder on the FTP server
          server-dir: public_html//sites/mobdesign/
          # Delete all files in the remote folder before uploading
          dangerous-clean-slate: true  
      