name: Projet MobDesign

on:
    push:
        branches: [main]

jobs:
  build-login-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Let's build the Docker image
        run: docker build -t mob-design .

      - name: Let's list the Docker images
        run: docker images

      - name: Let's login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Check the Docker images before pushing
        run: docker images

      - name: Now let's push the Docker image !
        run: |
            docker tag mob-design ${{ secrets.DOCKER_USERNAME }}/mob-design:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/mob-design:latest
